### ISSUE TITLE
Bootstrap for tables

### ISSUE THREAD

**Issue by luizpicolo** [vlado/rails_db_info#18]
What do you think of adding bootstrap?

![rails_db_info_bs](https://cloud.githubusercontent.com/assets/1373275/15169053/374e7cfe-1705-11e6-8391-3d4982cac93f.png)

**Comment by vlado** [comment]
Hi @luizpicolo, I was thinking about using something like bootstrap but I decided to make this gem as simple as possible and with as little dependencies as possible.

I'm aware that it doesn't look too good but I think it is a better approach to improve it with some custom CSS then to add bootstrap just to style simple table and few links.

I really like how you did it on screenshot :+1:
Maybe you can contribute something if you have time and check item number 1 in TODO list :) https://github.com/vlado/rails_db_info#todo--ideas

**Comment by luizpicolo** [comment]
Hello @vlado and thanks for your reaple.

I thought it would be so even, That his goal was a simple gem. I'll check your [TODO](https://github.com/vlado/rails_db_info#todo--ideas) list for more contributors.
